language: ruby
rvm:
- 2.1

before_script:
 - chmod +x ./scripts/cibuild  # 또는 로컬에서 직접 실행 후 커밋

# bundler 를 사용한다고 가정
# `install` 단계에 `bundle install` 이 디폴트로 실행
script: ./scripts/cibuild

branches:
 only:
 - develop
 - master
#  - /pages-(.*)/ # "pages-" 로 시작하는 모든 브랜치를 테스트 함

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # html-proofer 의 설치 속도 증가

notifications:
  email: false